name: Build
on: push
jobs:
  UbuntuRun:
    runs-on: self-hosted
    steps:  
      - run: nvcc -V  

      - name: Checkout
        uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir ${{github.workspace}}/build  

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ../

      - name: Run make
        working-directory: ${{github.workspace}}/build
        run: make -j      

      - run: echo "This job's status is ${{ job.status }}."

       # Run the tests using the downloaded build artifacts
      - name: Run CTest (Unit Tests)
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure
      
      

