name: Run Tests

on:
    workflow_run:
        workflows: ["Build"]
        types:
        - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Download the artifacts produced by the build workflow
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
      
      - name: Create build directory
        run: mkdir ${{github.workspace}}/build  

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ../

      - name: Run make
        working-directory: ${{github.workspace}}/build
        run: make -j
      
       # Verify that the artifacts were downloaded and extracted properly
      - name: List directory contents
        run: ls -la
      # Run the tests using the downloaded build artifacts
      - name: Run CTest (Unit Tests)
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure