name: Run Tests

on:
    workflow_run:
        workflows: ["Build"]
        types:
        - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Download the artifacts produced by the build workflow
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
      
       # Verify that the artifacts were downloaded and extracted properly
      - name: List directory contents
        run: ls -R ${{github.workspace}}/build

      # Run the tests using the downloaded build artifacts
      - name: Run CTest (Unit Tests)
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure